CAMERA_ID: 0
FRAME_HEIGHT: 720
FRAME_WIDTH: 1280
INITIAL_SCALE: 1.0
KALMAN_Q: 1.0e-05
KALMAN_R: 0.01
MAX_NUM_HANDS: 2
MAX_SCALE: 5.0
MIN_DETECTION_CONFIDENCE: 0.5
MIN_SCALE: 0.2
MIN_TRACKING_CONFIDENCE: 0.5
PINCH_THRESHOLD: 0.05
RESET_THRESHOLD: 0.8
SMOOTHING_FACTOR: 0.2
